# Setup
title:               Martin
tagline:             ''
description:         ''
url:                 https://martinmullins.github.io
baseurl:             '/blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Martin Mullins

# Gems
plugins:
  - jekyll-paginate
  - jekyll-target-blank

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
