# Setup
title:               Possible
tagline:             'Legacy Software Recovery'
description:         'I recover, understand, and modernize legacy software when source code is missing and support has ended. Serving Australian businesses.'
url:                 https://possiblenull.com
baseurl:             ''
permalink:           pretty
lang:                en-AU

# About/contact
author:
  name:              Martin Mullins
  url:               https://possiblenull.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-target-blank
  - jekyll-sitemap

# Custom vars
version:             2.0.2
google_analytics_id: #UA-XXXX-Y
og_image:            # https://possiblenull.com/public/og-image.png

# Lead capture
formspree_id:        xkolrzpb
